### PR TITLE
Update RAI-oss/FixedPointDecimal.jl to match JuliaMath: Fix constructor performance

### PR DESCRIPTION
**Pull request by ghost**
Pull in the changes to the base repo: Fix constructor performance (https://github.com/JuliaMath/FixedPointDecimals.jl/pull/30).

This improves on the `@generated` solution we took, by keeping the interface fully extensible.

### CODE REVIEW

**Comment by ghost** [comment]
@rbvermaa should I just hard reset back to their branch, or do a merge preserving our history?

**Comment by rbvermaa** [comment]
@rai-nhdaly Probably best to keep history to keep everything working (also later, if we need to build some old revision)

**Comment by ghost** [comment]
Sounds good, i'll do that!

**Comment by ghost** [comment]
Done.

**Comment by rai-nhdaly** [comment]
(Now we need to reevaluate the benchmarks in https://github.com/RelationalAI/raicode/issues/145)

**Pull request merged**
